import type { FoodItem } from "@/types/database";

/**
 * Uitgebreide Nederlandse standaard voedingsmiddelenbibliotheek.
 * Alle waarden zijn per 100 gram product gebaseerd op officiële voedingswaardetabellen (NEVO/USDA).
 * Standaard portiegroottes zijn ergonomisch afgestemd op de Nederlandse eetcultuur.
 */
export const DEFAULT_FOOD_ITEMS: Omit<FoodItem, "id" | "createdAt" | "updatedAt">[] = [
  // --- VLEES, VIS & EIEREN ---
  {
    name: "Kipfilet (gebakken/gegrild)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 165,
    proteinGramsPer100g: 31.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 3.6,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 150,
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Kalkoenfilet (gebakken)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 135,
    proteinGramsPer100g: 30.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 1.5,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 150,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Mager rundergehakt (gebakken)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 215,
    proteinGramsPer100g: 26.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 12.0,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 125,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Biefstuk (gebakken)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 140,
    proteinGramsPer100g: 27.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 3.5,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 150,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Zalmfilet (gebakken)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 208,
    proteinGramsPer100g: 22.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 13.0,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 125,
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Tonijn in eigen nat (uitlekgewicht)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 110,
    proteinGramsPer100g: 26.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 0.7,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 130, // 1 standaard blikje
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Ei (heel, gekookt)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 147,
    proteinGramsPer100g: 12.6,
    carbsGramsPer100g: 0.7,
    fatGramsPer100g: 10.6,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 55, // 1 gemiddeld ei (klasse M/L)
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Eiwit (vloeibaar / gekookt)",
    brand: null,
    category: "vlees_vis_ei",
    caloriesPer100g: 52,
    proteinGramsPer100g: 11.0,
    carbsGramsPer100g: 0.7,
    fatGramsPer100g: 0.2,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 100,
    isCustom: false,
    provenance: { source: "system" },
  },

  // --- ZUIVEL & PLANTAARDIGE VARIANTEN ---
  {
    name: "Magere Franse kwark",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 52,
    proteinGramsPer100g: 8.9,
    carbsGramsPer100g: 3.8,
    fatGramsPer100g: 0.1,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 250, // een kom
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Griekse yoghurt 0% vet",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 57,
    proteinGramsPer100g: 10.0,
    carbsGramsPer100g: 3.6,
    fatGramsPer100g: 0.0,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 200,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Hüttenkäse / Cottage cheese",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 92,
    proteinGramsPer100g: 12.3,
    carbsGramsPer100g: 2.6,
    fatGramsPer100g: 3.5,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 100,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Halfvolle melk",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 47,
    proteinGramsPer100g: 3.5,
    carbsGramsPer100g: 4.7,
    fatGramsPer100g: 1.5,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 200, // 1 glas
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Halfvolle kwark",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 78,
    proteinGramsPer100g: 9.5,
    carbsGramsPer100g: 3.5,
    fatGramsPer100g: 2.7,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 250,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Jonge kaas 30+",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 275,
    proteinGramsPer100g: 30.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 17.5,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 30, // 1 plak
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Skyr naturel",
    brand: null,
    category: "zuivel",
    caloriesPer100g: 63,
    proteinGramsPer100g: 11.0,
    carbsGramsPer100g: 4.0,
    fatGramsPer100g: 0.2,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 200,
    isCustom: false,
    provenance: { source: "system" },
  },

  // --- GRANEN & BROOD ---
  {
    name: "Havermout (fijn)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 375,
    proteinGramsPer100g: 13.5,
    carbsGramsPer100g: 62.0,
    fatGramsPer100g: 7.0,
    fiberGramsPer100g: 10.0,
    defaultPortionGrams: 50, // 1 portie
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Volkorenbrood",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 225,
    proteinGramsPer100g: 9.5,
    carbsGramsPer100g: 40.0,
    fatGramsPer100g: 2.2,
    fiberGramsPer100g: 6.8,
    defaultPortionGrams: 35, // 1 boterham
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Zilvervliesrijst (ongekookt)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 355,
    proteinGramsPer100g: 7.5,
    carbsGramsPer100g: 72.0,
    fatGramsPer100g: 2.5,
    fiberGramsPer100g: 4.0,
    defaultPortionGrams: 75, // 1 portie ongekookt
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Basmatirijst (ongekookt)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 350,
    proteinGramsPer100g: 8.5,
    carbsGramsPer100g: 77.0,
    fatGramsPer100g: 0.6,
    fiberGramsPer100g: 1.5,
    defaultPortionGrams: 75,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Volkoren pasta (ongekookt)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 345,
    proteinGramsPer100g: 13.0,
    carbsGramsPer100g: 64.0,
    fatGramsPer100g: 2.0,
    fiberGramsPer100g: 8.5,
    defaultPortionGrams: 80,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Zoete aardappel (rauw)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 86,
    proteinGramsPer100g: 1.6,
    carbsGramsPer100g: 17.5,
    fatGramsPer100g: 0.1,
    fiberGramsPer100g: 3.0,
    defaultPortionGrams: 150,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Aardappelen (gekookt)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 82,
    proteinGramsPer100g: 2.0,
    carbsGramsPer100g: 17.0,
    fatGramsPer100g: 0.1,
    fiberGramsPer100g: 1.8,
    defaultPortionGrams: 200,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Rijstwafel (naturel)",
    brand: null,
    category: "granen_brood",
    caloriesPer100g: 385,
    proteinGramsPer100g: 8.0,
    carbsGramsPer100g: 81.0,
    fatGramsPer100g: 2.8,
    fiberGramsPer100g: 3.1,
    defaultPortionGrams: 10, // 1 wafel
    isCustom: false,
    provenance: { source: "system" },
  },

  // --- GROENTE & FRUIT ---
  {
    name: "Banaan",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 89,
    proteinGramsPer100g: 1.1,
    carbsGramsPer100g: 20.0,
    fatGramsPer100g: 0.3,
    fiberGramsPer100g: 2.0,
    defaultPortionGrams: 120, // 1 middelgrote banaan zonder schil
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Appel (met schil)",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 54,
    proteinGramsPer100g: 0.4,
    carbsGramsPer100g: 12.0,
    fatGramsPer100g: 0.2,
    fiberGramsPer100g: 2.0,
    defaultPortionGrams: 135, // 1 handappel
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Blauwe bessen",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 57,
    proteinGramsPer100g: 0.7,
    carbsGramsPer100g: 11.5,
    fatGramsPer100g: 0.3,
    fiberGramsPer100g: 2.4,
    defaultPortionGrams: 100,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Aardbeien",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 32,
    proteinGramsPer100g: 0.7,
    carbsGramsPer100g: 5.5,
    fatGramsPer100g: 0.3,
    fiberGramsPer100g: 1.5,
    defaultPortionGrams: 100,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Broccoli (gekookt)",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 35,
    proteinGramsPer100g: 3.3,
    carbsGramsPer100g: 2.0,
    fatGramsPer100g: 0.6,
    fiberGramsPer100g: 3.0,
    defaultPortionGrams: 150,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Spinazie (rauw/vers)",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 23,
    proteinGramsPer100g: 2.9,
    carbsGramsPer100g: 0.6,
    fatGramsPer100g: 0.4,
    fiberGramsPer100g: 2.2,
    defaultPortionGrams: 100,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Avocado",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 160,
    proteinGramsPer100g: 2.0,
    carbsGramsPer100g: 1.5,
    fatGramsPer100g: 15.0,
    fiberGramsPer100g: 6.7,
    defaultPortionGrams: 70, // 0.5 avocado
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Paprika (rood)",
    brand: null,
    category: "groente_fruit",
    caloriesPer100g: 31,
    proteinGramsPer100g: 1.0,
    carbsGramsPer100g: 4.5,
    fatGramsPer100g: 0.3,
    fiberGramsPer100g: 2.1,
    defaultPortionGrams: 120, // 1 paprika
    isCustom: false,
    provenance: { source: "system" },
  },

  // --- PEULVRUCHTEN ---
  {
    name: "Kikkererwten (blik, uitlekgewicht)",
    brand: null,
    category: "peulvruchten",
    caloriesPer100g: 125,
    proteinGramsPer100g: 7.2,
    carbsGramsPer100g: 16.5,
    fatGramsPer100g: 2.2,
    fiberGramsPer100g: 5.5,
    defaultPortionGrams: 120,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Linzen (blik, uitlekgewicht)",
    brand: null,
    category: "peulvruchten",
    caloriesPer100g: 105,
    proteinGramsPer100g: 7.5,
    carbsGramsPer100g: 14.0,
    fatGramsPer100g: 0.8,
    fiberGramsPer100g: 4.8,
    defaultPortionGrams: 130,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Bruine bonen (blik, uitlekgewicht)",
    brand: null,
    category: "peulvruchten",
    caloriesPer100g: 110,
    proteinGramsPer100g: 8.0,
    carbsGramsPer100g: 14.5,
    fatGramsPer100g: 0.6,
    fiberGramsPer100g: 6.2,
    defaultPortionGrams: 125,
    isCustom: false,
    provenance: { source: "system" },
  },

  // --- NOTEN, ZADEN & VETTEN ---
  {
    name: "Pindakaas (100% pinda)",
    brand: null,
    category: "noten_zaden",
    caloriesPer100g: 620,
    proteinGramsPer100g: 26.0,
    carbsGramsPer100g: 11.0,
    fatGramsPer100g: 51.0,
    fiberGramsPer100g: 7.5,
    defaultPortionGrams: 20, // 1 ruime eetlepel
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Walnoten",
    brand: null,
    category: "noten_zaden",
    caloriesPer100g: 675,
    proteinGramsPer100g: 14.5,
    carbsGramsPer100g: 5.5,
    fatGramsPer100g: 65.0,
    fiberGramsPer100g: 6.0,
    defaultPortionGrams: 25, // 1 handje
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Amandelen (ongebrand)",
    brand: null,
    category: "noten_zaden",
    caloriesPer100g: 605,
    proteinGramsPer100g: 21.0,
    carbsGramsPer100g: 7.0,
    fatGramsPer100g: 52.0,
    fiberGramsPer100g: 10.0,
    defaultPortionGrams: 25,
    isCustom: false,
    provenance: { source: "system" },
  },
  {
    name: "Olijfolie (extra vierge)",
    brand: null,
    category: "oliën_sauzen",
    caloriesPer100g: 884,
    proteinGramsPer100g: 0.0,
    carbsGramsPer100g: 0.0,
    fatGramsPer100g: 100.0,
    fiberGramsPer100g: 0.0,
    defaultPortionGrams: 10, // 1 eetlepel
    isCustom: false,
    provenance: { source: "system" },
  },

  // --- SUPPLEMENTEN & SPORTVOEDING ---
  {
    name: "Whey proteïne poeder",
    brand: null,
    category: "supplementen",
    caloriesPer100g: 390,
    proteinGramsPer100g: 78.0,
    carbsGramsPer100g: 6.0,
    fatGramsPer100g: 5.5,
    fiberGramsPer100g: 1.0,
    defaultPortionGrams: 30, // 1 maatschep (scoop)
    isCustom: false,
    isFavorite: true,
    provenance: { source: "system" },
  },
  {
    name: "Caseïne proteïne poeder",
    brand: null,
    category: "supplementen",
    caloriesPer100g: 360,
    proteinGramsPer100g: 77.0,
    carbsGramsPer100g: 4.5,
    fatGramsPer100g: 2.0,
    fiberGramsPer100g: 0.5,
    defaultPortionGrams: 30,
    isCustom: false,
    provenance: { source: "system" },
  },
];
