import type { Exercise } from "@/types/database";

const SYSTEM_PROVENANCE = {
  source: "system" as const,
  isDemo: false,
};

const DEFAULT_CREATED_AT = "2026-01-01T00:00:00.000Z";

export const DEFAULT_EXERCISES: Exercise[] = [
  // =========================================================================
  // BORST (CHEST)
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e001",
    name: "Bankdrukken (Barbell)",
    alternativeNames: ["Bench Press", "Flat Barbell Bench Press", "Borstdrukken"],
    category: "kracht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["schouders", "armen"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Lig stabiel op de bank met de voeten plat op de grond. Trek de schouderbladen naar elkaar toe en omlaag. Laat de stang beheerst zakken tot het midden van de borst en druk krachtig uit zonder de billen van de bank te tillen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e007",
    name: "Schuin Bankdrukken (Dumbbell)",
    alternativeNames: ["Incline Dumbbell Press", "Incline DB Bench Press"],
    category: "kracht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["schouders", "armen"],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Stel de trainingsbank in op circa 30 graden helling. Breng de dumbbells gecontroleerd omlaag tot borsthoogte met de ellebogen in een hoek van ongeveer 45 tot 60 graden ten opzichte van het bovenlichaam en druk explosief uit.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e013",
    name: "Opdrukken (Push-up)",
    alternativeNames: ["Push-up", "Opdrukken", "Pushup"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["schouders", "armen", "core"],
    equipment: "lichaamsgewicht",
    measurementType: "lichaamsgewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de handen iets breder dan schouderbreedte op de grond en houd het lichaam in een kaarsrechte plankpositie. Zak gecontroleerd totdat de borst de vloer bijna raakt en druk stevig omhoog.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e014",
    name: "Borstdrukken Machine",
    alternativeNames: ["Chest Press Machine", "Seated Chest Press"],
    category: "kracht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["schouders", "armen"],
    equipment: "machine",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Stel de zithoogte zo in dat de handgrepen ter hoogte van het midden van de borst staan. Druk de grepen gelijkmatig naar voren en laat het gewicht beheerst terugkeren zonder de gewichten volledig te laten rusten.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e015",
    name: "Kabel Flyes",
    alternativeNames: ["Cable Flyes", "Cable Crossover", "Kabel Kruisen"],
    category: "kracht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["schouders"],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Pak de handvatten vast en stap iets naar voren in een stabiele spreidstand. Houd een lichte buiging in de ellebogen en breng de handen in een wijde omarmende beweging naar elkaar toe.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e016",
    name: "Dips (Lichaamsgewicht)",
    alternativeNames: ["Chest Dips", "Parallel Bar Dips", "Dippen"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["armen", "schouders"],
    equipment: "lichaamsgewicht",
    measurementType: "lichaamsgewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Leun licht voorover om de nadruk op de borst te leggen. Zak beheerst door de ellebogen tot ongeveer 90 graden en druk krachtig terug omhoog zonder de ellebogen hard te overstrekken.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e017",
    name: "Verzwaarde Dips",
    alternativeNames: ["Weighted Dips", "Dips met Gewicht"],
    category: "kracht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["armen", "schouders"],
    equipment: "lichaamsgewicht",
    measurementType: "extra_gewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Dips uitgevoerd met extra ballast aan een dipgordel of dumbbell tussen de benen. Voer de beweging strikt en gecontroleerd uit.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e018",
    name: "Geassisteerde Dips",
    alternativeNames: ["Assisted Dips Machine", "Ondersteunde Dips"],
    category: "kracht",
    primaryMuscleGroup: "borst",
    secondaryMuscleGroups: ["armen", "schouders"],
    equipment: "machine",
    measurementType: "assisted",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de knieën of voeten op het tegengewicht-platform van het assistentie-apparaat. Kies het tegengewicht om het lichaamsgewicht gecontroleerd te ontlasten.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },

  // =========================================================================
  // RUG (BACK)
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e003",
    name: "Conventionele Deadlift",
    alternativeNames: ["Conventional Deadlift", "Barbell Deadlift", "Kruistillen"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["benen", "core", "armen"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de voeten op heupbreedte onder de stang. Pak de stang net buiten de benen vast, trek de rug strak en recht, en til het gewicht synchroon op door knieën en heupen krachtig te strekken.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e005",
    name: "Voorovergebogen Roeien (Barbell)",
    alternativeNames: ["Barbell Bent-Over Row", "Barbell Row", "Pendlay Row"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "schouders", "core"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Scharnier vanuit de heupen voorover met een rechte rug tot circa 45 graden. Trek de stang beheerst naar de onderbuik en knijp de schouderbladen bewust samen bovenin.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e006",
    name: "Optrekken (Pull-up)",
    alternativeNames: ["Pull-up", "Overhandse Pull-up", "Chin-up"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "core"],
    equipment: "lichaamsgewicht",
    measurementType: "lichaamsgewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Hang volledig uit aan de stang met een bovenhandse greep. Trek het lichaam omhoog tot de kin over de stang reikt en zak gecontroleerd terug naar de uitgangspositie.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e019",
    name: "Verzwaard Optrekken",
    alternativeNames: ["Weighted Pull-up", "Optrekken met Gewicht"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "core"],
    equipment: "lichaamsgewicht",
    measurementType: "extra_gewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Optrekken met extra gewicht aan een dipriem of dumbbell tussen de voeten. Trek explosief omhoog en bewaar een rustig tempo in de neerwaartse fase.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e020",
    name: "Geassisteerd Optrekken",
    alternativeNames: ["Assisted Pull-up Machine", "Ondersteund Optrekken"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "core"],
    equipment: "machine",
    measurementType: "assisted",
    isCustom: false,
    isArchived: false,
    instructions:
      "Kies een passend tegengewicht op het apparaat. Plaats de knieën op het platform en voer een volledige optrekbeweging uit over de gehele bewegingsbaan.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e021",
    name: "Lat Pulldown",
    alternativeNames: ["Kabel Lat Pulldown", "Wide Grip Lat Pulldown"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "schouders"],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Ga rechtop zitten met de bovenbenen stevig onder de rolkussens. Pak de stang breed vast, trek de stang gecontroleerd naar de bovenkant van de borst en knijp de rugspieren aan.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e022",
    name: "Zittend Kabelroeien",
    alternativeNames: ["Seated Cable Row", "Kabelroeien smal"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "core"],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Zit met licht gebogen knieën en een kaarsrechte rug. Trek de V-greep naar de navel terwijl je de schouderbladen stevig samenknijpt.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e023",
    name: "Enkelarmige Dumbbell Row",
    alternativeNames: ["One-Arm Dumbbell Row", "Single Arm DB Row"],
    category: "kracht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "core"],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats één knie en hand op de trainingsbank voor ondersteuning. Trek de dumbbell met de andere hand in een boog naar de heup zonder de romp te verdraaien.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e024",
    name: "Uithangen aan Stang",
    alternativeNames: ["Dead Hang", "Uithangen", "Bar Hang"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "rug",
    secondaryMuscleGroups: ["armen", "schouders", "core"],
    equipment: "lichaamsgewicht",
    measurementType: "tijd",
    isCustom: false,
    isArchived: false,
    instructions:
      "Pak de optrekstang met beide handen vast en hang volledig ontspannen uit. Verbetert grijpkracht, rekt de rugwervels en opent de schouders.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },

  // =========================================================================
  // BENEN & BILLEN (LEGS & GLUTES)
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e002",
    name: "Kniebuigen (Barbell Back Squat)",
    alternativeNames: ["Barbell Squat", "Back Squat", "Kniebuigen"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["core", "rug"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de stang stabiel op de monnikskapsspier (trapezius). Zet de voeten schouderbreedte neer, duw de knieën naar buiten in het verlengde van de tenen en zak tot minimaal parallel.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e008",
    name: "Roemeense Deadlift (RDL)",
    alternativeNames: ["Romanian Deadlift", "RDL", "Hamstring Deadlift"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["rug", "core"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Houd de knieën licht gebogen en stijf. Duw de heupen zo ver mogelijk naar achteren terwijl de stang vlak langs de schenen zakt voor maximale spanning op de hamstrings.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e025",
    name: "Beenpers (Leg Press 45°)",
    alternativeNames: ["Leg Press", "Beenpers Machine", "45 Degree Leg Press"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["kuiten"],
    equipment: "machine",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de voeten heupbreedte op het platform. Laat het gewicht gecontroleerd zakken zonder dat de onderrug van het zitkussen loskomt en duw gecontroleerd omhoog zonder de knieën op slot te gooien.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e026",
    name: "Beencurl Liggend",
    alternativeNames: ["Lying Leg Curl", "Hamstring Curl"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["kuiten"],
    equipment: "machine",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Lig plat op de buik met de rolkussens net onder de kuiten. Buig de benen krachtig naar het zitvlak en laat het gewicht beheerst terugkeren.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e027",
    name: "Beenstrekken (Leg Extension)",
    alternativeNames: ["Leg Extension", "Quadriceps Extension"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: [],
    equipment: "machine",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Zit stevig tegen de rugleuning en strek de benen tot ze bijna horizontaal zijn. Knijp de quadriceps één seconde bewust samen en laat langzaam zakken.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e028",
    name: "Uitvalspassen (Dumbbell Lunges)",
    alternativeNames: ["Walking Lunges", "Dumbbell Lunges", "Uitvalspassen"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["core", "kuiten"],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Houd een dumbbell in iedere hand. Stap met één been naar voren en zak totdat beide knieën in een hoek van 90 graden staan. Druk terug omhoog en wissel van been.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e029",
    name: "Bulgarian Split Squat",
    alternativeNames: ["Split Squat", "Bulgaarse Squat", "Rear Foot Elevated Split Squat"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["core"],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de wreef van de achterste voet op een fitnessbankje. Zak diep door het voorste been waarbij het bovenlichaam licht naar voren leunt voor maximale bil- en quadricepsactivatie.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e030",
    name: "Heupstoot (Barbell Hip Thrust)",
    alternativeNames: ["Hip Thrust", "Glute Bridge", "Bekkenheffen"],
    category: "kracht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["core"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de bovenrug tegen een bank en leg de stang op de heupen (met padding). Druk krachtig door de hielen omhoog tot de heupen volledig gestrekt zijn en knijp de billen 2 seconden samen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e031",
    name: "Muurzitten (Wall Sit)",
    alternativeNames: ["Wall Sit", "Muurzit", "Statische Muurzit"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["core", "kuiten"],
    equipment: "lichaamsgewicht",
    measurementType: "tijd",
    isCustom: false,
    isArchived: false,
    instructions:
      "Plaats de rug plat tegen de muur en zak door totdat de bovenbenen evenwijdig aan de grond zijn in een hoek van 90 graden. Houd deze statische positie vast voor de opgegeven tijdsduur.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e032",
    name: "Lichaamsgewicht Kniebuigen",
    alternativeNames: ["Air Squat", "Bodyweight Squat", "Vrije Kniebuiging"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "benen",
    secondaryMuscleGroups: ["core"],
    equipment: "lichaamsgewicht",
    measurementType: "lichaamsgewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Squat uitsluitend met het eigen lichaamsgewicht. Zak diep met de borst fier vooruit en druk gecontroleerd omhoog vanuit de hielen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },

  // =========================================================================
  // KUITEN (CALVES)
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e033",
    name: "Staand Kuitheffen",
    alternativeNames: ["Standing Calf Raise", "Kuitheffen Staand"],
    category: "kracht",
    primaryMuscleGroup: "kuiten",
    secondaryMuscleGroups: [],
    equipment: "machine",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Ga met de bal van de voet op het randje van het platform staan. Zak diep voor een volledige rek op de kuit en druk explosief omhoog tot op de tenen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e034",
    name: "Zittend Kuitheffen",
    alternativeNames: ["Seated Calf Raise", "Kuitheffen Zittend"],
    category: "kracht",
    primaryMuscleGroup: "kuiten",
    secondaryMuscleGroups: [],
    equipment: "machine",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Zit met de knieën onder het kussen. Richt zich specifiek op de soleus-spier in de kuit door de gebogen kniestand.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },

  // =========================================================================
  // SCHOUDERS (SHOULDERS)
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e004",
    name: "Schouderdrukken (Overhead Press)",
    alternativeNames: ["OHP", "Overhead Press", "Military Press", "Barbell Shoulder Press"],
    category: "kracht",
    primaryMuscleGroup: "schouders",
    secondaryMuscleGroups: ["armen", "core"],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Sta rechtop met aangespannen buik- en bilspieren. Druk de stang verticaal omhoog vanaf de bovenkant van de borst en beweeg het hoofd licht naar voren zodra de stang het voorhoofd passeert.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e009",
    name: "Zijwaarts Heffen (Dumbbell Lateral Raise)",
    alternativeNames: ["Dumbbell Lateral Raise", "Side Raise", "Zijwaarts Heffen"],
    category: "kracht",
    primaryMuscleGroup: "schouders",
    secondaryMuscleGroups: [],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Sta stevig met de dumbbells langs het lichaam. Breng de armen zijwaarts omhoog tot schouderhoogte met de pinken licht omhoog gedraaid en zonder te zwaaien met het bovenlichaam.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e035",
    name: "Zittend Dumbbell Schouderdrukken",
    alternativeNames: ["Seated Dumbbell Shoulder Press", "DB Overhead Press"],
    category: "kracht",
    primaryMuscleGroup: "schouders",
    secondaryMuscleGroups: ["armen"],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Zit rechtop tegen een steile rugleuning. Druk de dumbbells vanuit schouderhoogte gelijktijdig omhoog tot ze boven het hoofd bijna samenkomen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e036",
    name: "Kabel Zijwaarts Heffen",
    alternativeNames: ["Cable Lateral Raise", "Single Arm Cable Lateral"],
    category: "kracht",
    primaryMuscleGroup: "schouders",
    secondaryMuscleGroups: [],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Gebruik een lage katrol. Zorgt voor constante weerstand over het volledige bereik van de beweging van de zijkant van de schouder.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e037",
    name: "Face Pull",
    alternativeNames: ["Face Pull", "Kabel Face Pull", "Achterste Schouder Pull"],
    category: "kracht",
    primaryMuscleGroup: "schouders",
    secondaryMuscleGroups: ["rug"],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Bevestig het touw op ooghoogte. Trek het touw naar het gezicht toe en spreid de polsen naar buiten voor optimale versterking van de rotatormanchet en achterste schouderkoppen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },

  // =========================================================================
  // ARMEN (ARMS - BICEPS & TRICEPS)
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e010",
    name: "Biceps Curl (Barbell)",
    alternativeNames: ["Barbell Bicep Curl", "Biceps Curl", "Barbell Curl"],
    category: "kracht",
    primaryMuscleGroup: "armen",
    secondaryMuscleGroups: [],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Houd de ellebogen strak tegen de zijde van het lichaam gedrukt. Buig de onderarmen omhoog tot maximale piekcontractie van de biceps en laat gecontroleerd zakken.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e011",
    name: "Triceps Kabel Pushdown",
    alternativeNames: ["Triceps Pushdown", "Cable Pushdown", "Rope Pushdown"],
    category: "kracht",
    primaryMuscleGroup: "armen",
    secondaryMuscleGroups: [],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Houd de ellebogen gefixeerd langs de romp. Duw het touw krachtig naar beneden en spreid de uiteinden onderaan voor maximale tricepsaanspanning.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e038",
    name: "Hamer Curl (Dumbbell Hammer Curl)",
    alternativeNames: ["Hammer Curl", "Dumbbell Hammer Curl", "Neutrale Curl"],
    category: "kracht",
    primaryMuscleGroup: "armen",
    secondaryMuscleGroups: [],
    equipment: "dumbbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Houd de dumbbells met neutrale handpalmen naar elkaar gericht. Buig omhoog om de brachialis en onderarmspieren intensief aan te spreken.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e039",
    name: "Triceps Schedelbreekers (EZ-bar)",
    alternativeNames: ["Skull Crushers", "Lying Triceps Extension", "EZ Bar Skull Crusher"],
    category: "kracht",
    primaryMuscleGroup: "armen",
    secondaryMuscleGroups: [],
    equipment: "barbell",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Lig op een vlakke bank met een EZ-stang boven de borst. Buig uitsluitend de onderarmen naar het voorhoofd en strek krachtig uit zonder de bovenarmen te verplaatsen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },

  // =========================================================================
  // CORE & BUIKSPIEREN
  // =========================================================================
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e012",
    name: "Plank",
    alternativeNames: ["Plank", "Forearm Plank", "Buikspierplank"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "core",
    secondaryMuscleGroups: ["schouders", "benen"],
    equipment: "lichaamsgewicht",
    measurementType: "tijd",
    isCustom: false,
    isArchived: false,
    instructions:
      "Steun op de onderarmen en de tenen. Houd het hele lichaam in een kaarsrechte lijn van kruin tot hielen en span buik, rug en billen krachtig aan voor de doelduur.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e040",
    name: "Zijwaartse Plank (Side Plank)",
    alternativeNames: ["Side Plank", "Zijplank"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "core",
    secondaryMuscleGroups: ["schouders"],
    equipment: "lichaamsgewicht",
    measurementType: "tijd",
    isCustom: false,
    isArchived: false,
    instructions:
      "Steun op één onderarm en de zijkant van de voet. Houd de heupen hoog van de grond zodat het lichaam een rechte diagonale lijn vormt. Versterkt de schuine buikspieren.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e041",
    name: "Hangend Knieheffen",
    alternativeNames: ["Hanging Knee Raise", "Hanging Leg Raise", "Knieheffen"],
    category: "lichaamsgewicht",
    primaryMuscleGroup: "core",
    secondaryMuscleGroups: ["armen"],
    equipment: "lichaamsgewicht",
    measurementType: "lichaamsgewicht",
    isCustom: false,
    isArchived: false,
    instructions:
      "Hang aan een optrekstang. Breng de knieën gecontroleerd omhoog naar de borst door het bekken naar achteren te kantelen, zonder te zwaaien met het lichaam.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
  {
    id: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e042",
    name: "Kabel Woodchopper",
    alternativeNames: ["Cable Woodchopper", "Rotational Cable Chop"],
    category: "kracht",
    primaryMuscleGroup: "core",
    secondaryMuscleGroups: ["schouders"],
    equipment: "kabel",
    measurementType: "gewicht_herhalingen",
    isCustom: false,
    isArchived: false,
    instructions:
      "Pak de handgreep met gestrekte armen vast en roteer de romp diagonaal van hoog naar laag (of omgekeerd) om de rotationele kracht en schuine buikspieren te trainen.",
    videoUrl: null,
    provenance: SYSTEM_PROVENANCE,
    createdAt: DEFAULT_CREATED_AT,
  },
];
