import type {
  WorkoutRoutine,
  RoutineDay,
  PlannedExerciseInDay,
} from "@/types/database";

export interface RoutineTemplate {
  id: string;
  name: string;
  description: string;
  splitDescription: string;
  days: {
    name: string;
    dayIndex: number;
    plannedExercises: PlannedExerciseInDay[];
  }[];
}

export const ROUTINE_TEMPLATES: RoutineTemplate[] = [
  // =========================================================================
  // 1. FULL BODY (3 DAGEN PER WEEK)
  // =========================================================================
  {
    id: "template-full-body-3d",
    name: "Full Body Basis (3 Dagen)",
    description:
      "Ideaal voor beginners tot gemiddelde sporters. Traint het gehele lichaam 3 keer per week met focus op samengestelde basisoefeningen.",
    splitDescription: "3 trainingsdagen (bijv. Ma / Wo / Vr)",
    days: [
      {
        name: "Dag A (Squat & Borst Focus)",
        dayIndex: 1,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e002",
            exerciseName: "Kniebuigen (Barbell Back Squat)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
            notes: "Focus op diepte en rechte rug.",
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e001",
            exerciseName: "Bankdrukken (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
            notes: "Schouderbladen intrekken.",
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e005",
            exerciseName: "Voorovergebogen Roeien (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e012",
            exerciseName: "Plank",
            measurementType: "tijd",
            targetSets: 3,
            targetDurationSeconds: 45,
            effortScale: "geen",
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Dag B (Deadlift & Schouders Focus)",
        dayIndex: 2,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e003",
            exerciseName: "Conventionele Deadlift",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 5,
            targetRepsMax: 5,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8.5,
            restSeconds: 150,
            notes: "Spanning opbouwen voor de lift.",
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e004",
            exerciseName: "Schouderdrukken (Overhead Press)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e021",
            exerciseName: "Lat Pulldown",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e041",
            exerciseName: "Hangend Knieheffen",
            measurementType: "lichaamsgewicht",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            effortScale: "geen",
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Dag C (Benen & Hypertrofie Focus)",
        dayIndex: 3,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e029",
            exerciseName: "Bulgarian Split Squat",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e007",
            exerciseName: "Schuin Bankdrukken (Dumbbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e010",
            exerciseName: "Biceps Curl (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e011",
            exerciseName: "Triceps Kabel Pushdown",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 2. UPPER / LOWER SPLIT (4 DAGEN PER WEEK)
  // =========================================================================
  {
    id: "template-upper-lower-4d",
    name: "Upper / Lower Split (4 Dagen)",
    description:
      "Klassieke 4-daagse split die bovenlichaam en onderlichaam afwisselt. Biedt uitstekende hersteltijd en ruimte voor hogere trainingsvolumes.",
    splitDescription: "4 trainingsdagen (bijv. Ma / Di / Do / Vr)",
    days: [
      {
        name: "Upper A (Kracht)",
        dayIndex: 1,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e001",
            exerciseName: "Bankdrukken (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e005",
            exerciseName: "Voorovergebogen Roeien (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e004",
            exerciseName: "Schouderdrukken (Overhead Press)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e010",
            exerciseName: "Biceps Curl (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Lower A (Squat Focus)",
        dayIndex: 2,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e002",
            exerciseName: "Kniebuigen (Barbell Back Squat)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8.5,
            restSeconds: 150,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e008",
            exerciseName: "Roemeense Deadlift (RDL)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e027",
            exerciseName: "Beenstrekken (Leg Extension)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 60,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e012",
            exerciseName: "Plank",
            measurementType: "tijd",
            targetSets: 3,
            targetDurationSeconds: 60,
            effortScale: "geen",
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Upper B (Hypertrofie)",
        dayIndex: 3,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e007",
            exerciseName: "Schuin Bankdrukken (Dumbbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e006",
            exerciseName: "Optrekken (Pull-up)",
            measurementType: "lichaamsgewicht",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 10,
            effortScale: "rpe",
            targetRpe: 8.5,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e009",
            exerciseName: "Zijwaarts Heffen (Dumbbell Lateral Raise)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 12,
            targetRepsMax: 15,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e011",
            exerciseName: "Triceps Kabel Pushdown",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Lower B (Deadlift Focus)",
        dayIndex: 4,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e003",
            exerciseName: "Conventionele Deadlift",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 5,
            targetRepsMax: 5,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 9,
            restSeconds: 180,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e025",
            exerciseName: "Beenpers (Leg Press 45°)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e026",
            exerciseName: "Beencurl Liggend",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 60,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e033",
            exerciseName: "Staand Kuitheffen",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 12,
            targetRepsMax: 15,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 3. PUSH / PULL / LEGS (3 DAGEN SPLIT)
  // =========================================================================
  {
    id: "template-ppl-3d",
    name: "Push / Pull / Legs (PPL - 3 Dagen)",
    description:
      "Verdeelt spieren op basis van bewegingspatronen (duwen, trekken en benen). Maximale spierspecifieke focus en intensiteit.",
    splitDescription: "3 trainingsdagen (of herhalen in een 6-daagse cyclus)",
    days: [
      {
        name: "Push (Borst, Schouders, Triceps)",
        dayIndex: 1,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e001",
            exerciseName: "Bankdrukken (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e004",
            exerciseName: "Schouderdrukken (Overhead Press)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e007",
            exerciseName: "Schuin Bankdrukken (Dumbbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e016",
            exerciseName: "Dips (Lichaamsgewicht)",
            measurementType: "lichaamsgewicht",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 12,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e011",
            exerciseName: "Triceps Kabel Pushdown",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 15,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Pull (Rug, Biceps, Achterkant Schouders)",
        dayIndex: 2,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e003",
            exerciseName: "Conventionele Deadlift",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 5,
            targetRepsMax: 5,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8.5,
            restSeconds: 180,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e005",
            exerciseName: "Voorovergebogen Roeien (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e021",
            exerciseName: "Lat Pulldown",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e037",
            exerciseName: "Face Pull",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 12,
            targetRepsMax: 15,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e010",
            exerciseName: "Biceps Curl (Barbell)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Legs (Benen, Kuiten, Core)",
        dayIndex: 3,
        plannedExercises: [
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e002",
            exerciseName: "Kniebuigen (Barbell Back Squat)",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 6,
            targetRepsMax: 8,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8.5,
            restSeconds: 150,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e008",
            exerciseName: "Roemeense Deadlift (RDL)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 8,
            targetRepsMax: 10,
            targetWeightKg: null,
            effortScale: "rpe",
            targetRpe: 8,
            restSeconds: 120,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e025",
            exerciseName: "Beenpers (Leg Press 45°)",
            measurementType: "gewicht_herhalingen",
            targetSets: 3,
            targetRepsMin: 10,
            targetRepsMax: 12,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 2,
            restSeconds: 90,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e033",
            exerciseName: "Staand Kuitheffen",
            measurementType: "gewicht_herhalingen",
            targetSets: 4,
            targetRepsMin: 12,
            targetRepsMax: 15,
            targetWeightKg: null,
            effortScale: "rir",
            targetRir: 1,
            restSeconds: 60,
          },
          {
            exerciseId: "e4a77e80-8b1b-4b10-9fc6-2b4a3901e041",
            exerciseName: "Hangend Knieheffen",
            measurementType: "lichaamsgewicht",
            targetSets: 3,
            targetRepsMin: 12,
            targetRepsMax: 15,
            effortScale: "geen",
            restSeconds: 60,
          },
        ],
      },
    ],
  },
];

/**
 * Zet een sjabloon om in een bewerkbaar, in-memory schema-object met unieke UUIDs.
 * Wordt NIET automatisch opgeslagen in de database totdat de gebruiker op Opslaan klikt.
 */
export function instantiateTemplate(
  templateId: string,
  customName?: string
): { routine: WorkoutRoutine; days: RoutineDay[] } | null {
  const template = ROUTINE_TEMPLATES.find((t) => t.id === templateId);
  if (!template) return null;

  const routineId = crypto.randomUUID();
  const now = new Date().toISOString();

  const routine: WorkoutRoutine = {
    id: routineId,
    name: customName || template.name,
    description: template.description,
    version: 1,
    isActive: false,
    isArchived: false,
    provenance: { source: "user", isDemo: false },
    createdAt: now,
    updatedAt: now,
  };

  const days: RoutineDay[] = template.days.map((d, idx) => ({
    id: crypto.randomUUID(),
    routineId,
    dayIndex: d.dayIndex || idx + 1,
    name: d.name,
    plannedExercises: d.plannedExercises.map((pe) => ({ ...pe })),
    createdAt: now,
  }));

  return { routine, days };
}
